name: "📝 General Issue"
description: Report a bug or request a new feature
title: "[ISSUE]: "
labels: []
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Issue
      description: What type of issue are you reporting?
      options:
        - Bug Report
        - Feature Request
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report Section  
        *(Fill this out if you selected “Bug Report” above)*

  - type: input
    id: bug_summary
    attributes:
      label: Bug Summary
      description: A concise summary of the bug.
      placeholder: e.g. App crashes when opening a file
    validations:
      required: false

  - type: textarea
    id: bug_steps
    attributes:
      label: Steps to Reproduce
      description: List all steps needed to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe error
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version / Commit Hash
      description: Version or commit hash where this issue occurs.
      placeholder: e.g. v1.2.3 or abc123
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request Section  
        *(Fill this out if you selected “Feature Request” above)*

  - type: input
    id: feature_summary
    attributes:
      label: Feature Summary
      description: A short description of the feature or enhancement.
      placeholder: e.g. Add dark mode support
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: Explain the use case or pain point.
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: Describe your proposed workflow or design.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you looked into other options or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any extra information, screenshots, or mockups.
    validations:
      required: false
